name: Python Test Workflow

on:
  push:
  workflow_dispatch:
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Greet the User
        run: python3 -m unittest test_utils.py
